### ISSUE TITLE
Error upon saving edited value

### ISSUE THREAD

**Issue by code76kb** [CarlosNZ/json-edit-react#24] opened 2024-01-23 08:18 UTC
Getting this upon saving edited value

```
Uncaught (in promise) TypeError: Object(...) is not a function
    le index.esm.js:1
    onEdit index.esm.js:1
    v index.esm.js:1
    v index.esm.js:1
    onEdit index.esm.js:1
    L index.esm.js:1
    React 14
    unstable_runWithPriority scheduler.development.js:468
    React 4
```

the implementation 
  
 ```
<JsonEditor
                    data={{ test: 1, test2: 2, test3: 3 }}
                     // enableClipboard={true}
                     // restrictEdit={false}
                     // restrictDelete={true}
                     // restrictAdd={true}
                     // restrictTypeSelection={true}
                     onEdit={(data)=>{
                              console.log(TAG,"OnEdit...");
                     }}
                     onUpdate={(data) => {
                            console.log(TAG, "OnUpdate :", data);
                     }}
  />

```

**Comment by code76kb** [comment] 2024-01-23 11:27
Yes, I tried downgrading to the previous version but still the same

**Comment by CarlosNZ** [comment] 2024-01-23 19:46
> Although the implementation is in a class based component, with vanilla js not type script

Hmm, that shouldn't really matter. Might need a little more context -- can you share a larger section of your code? Which version of React are you using?

Also, can you try using specific build versions, either with

```js
import { JsonEditor } from 'json-edit-react/build/index.esm'
```
or
```js
import { JsonEditor } from 'json-edit-react/build/index.cjs
```

See if that makes a difference?

**Comment by code76kb** [comment] 2024-01-24 05:47
.......Versions 

   "react": "^17.0.2",
   "react-dom": "^17.0.2",
    
.......Import Statement 

`import { JsonEditor } from 'json-edit-react'`
    
    

.......................Rendering inside '@material-ui' Dialog Component ....... 

 

```
renderConfigUpdateDialog = () => {
        const data = this.state.config ? JSON.parse(JSON.stringify(this.state.config)) : null; //{ test: "1", test2: "2", test3: "3" };
        console.log(TAG, "renderConfigUpdateDialog :", data);
        return (
            <Dialog
                fullWidth={true}
                maxWidth={'md'}
                open={this.state.openConfigViewDialog}
                keepMounted
                onClose={this.props.onClose}
                aria-labelledby="alert-dialog-slide-title"
                aria-describedby="alert-dialog-slide-description"
            >
                <DialogTitle id="alert-dialog-slide-title">{`ServiceId : ${data.serviceId}`}</DialogTitle>

                <DialogContent>
                    <Fragment>
                        {data ?

                            <ReactJson 
                                src={data}
                                displayDataTypes={true}
                                onEdit={(data) => {
                                    this.setState({  config:data.updated_src, editedConfig: data.updated_src, disableUpdateBtn: false })
                                }} />

                            // <JsonEditor
                            //     data={{ test: 1, test2: 2, test3: 3 }}
                            //     // enableClipboard={true}
                            //     // restrictEdit={false}
                            //     // restrictDelete={true}
                            //     // restrictAdd={true}
                            //     // restrictTypeSelection={true}
                            //     onEdit={(data)=>{
                            //         console.log(TAG,"OnEdit...");
                            //     }}
                            //     onUpdate={(data) => {
                            //         console.log(TAG, "OnUpdate :", data);
                            //     }}
                            // />

                            : null}

                    </Fragment>
                </DialogContent>


                <DialogActions>
                    <Button variant="contained" onClick={this.updateRunTimeConfig} color="primary" disabled={this.state.disableUpdateBtn}>
                        Update
                    </Button>
                    <Button variant="contained" onClick={() => {
                        this.setState({ openConfigViewDialog: false,  });
                    }} >
                        Cannel
                    </Button>
                </DialogActions>
            </Dialog>
        );
    }
```

**Comment by CarlosNZ** [comment] 2024-01-24 10:04
Hi @code76kb , I set up a quick new project using React 17.0.2 and Material-UI and I used your code as a starting point and ended up with this to get it working:
```jsx
import React from "react";
import { JsonEditor } from "json-edit-react";
import { Dialog, DialogContent, DialogTitle, DialogActions, Button } from "@mui/material";

class App extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      config: { test: 1, test2: 2, test3: 3 },
      openConfigViewDialog: true,
    };
  }

  handleSave = () => {
    // Save the updated config to ???
    console.log("The current config to save is:", this.state.config);
  };

  render() {
    const data = this.state.config ? JSON.parse(JSON.stringify(this.state.config)) : null; //{ test: "1", test2: "2", test3: "3" };
    console.log(this.state);
    return (
      <Dialog
        fullWidth={true}
        maxWidth={"md"}
        open={this.state.openConfigViewDialog}
        keepMounted
        aria-labelledby="alert-dialog-slide-title"
        aria-describedby="alert-dialog-slide-description"
      >
        <DialogTitle id="alert-dialog-slide-title">{`ServiceId : ${this.state.serviceId}`}</DialogTitle>
        <DialogContent>
          <>
            <JsonEditor
              data={data}
              enableClipboard={true}
              restrictEdit={false}
              restrictDelete={true}
              restrictAdd={true}
              restrictTypeSelection={true}
              // onEdit={(data) => {
              //   console.log("OnEdit...", data.newData);
              //   // setData(data.newData);
              // }}
              onUpdate={(data) => {
                console.log("OnUpdate :", data.newData);
                this.setState({ config: data.newData });
              }}
            />
          </>
        </DialogContent>

        <DialogActions>
          <Button variant="contained" onClick={this.handleSave} color="primary" disabled={this.state.disableUpdateBtn}>
            Update
          </Button>
          <Button
            variant="contained"
            onClick={() => {
              this.setState({ openConfigViewDialog: false });
            }}
          >
            Cancel
          </Button>
        </DialogActions>
      </Dialog>
    );
  }
}

export default App;
```

I think the problem you're having is because you weren't managing the local state of `data` using `JsonEditor`'s `onUpdate` (or `onEdit`) method. So even though the data was changing visually (and inside `json-edit-react`), you didn't have access to this value when you pressed the "Update" button and tried to run `this.updateRunTimeConfig`.

You'll see in my example above that `onUpdate` sets the local config state, and then runs `handleSave' on click which would then do something with this value. 

This is working for me:

Starting state:
<img width="918" alt="Screenshot 2024-01-24 at 11 00 28 PM" src="https://github.com/CarlosNZ/json-edit-react/assets/5456533/0757a489-c5d6-4e3c-9c2d-581546e45d66">

After changing some values:
<img width="953" alt="Screenshot 2024-01-24 at 11 01 06 PM" src="https://github.com/CarlosNZ/json-edit-react/assets/5456533/2a5a3d60-5c5b-46a0-b036-7948d43dcd05">

Then in the console, when clicking "Update":
<img width="418" alt="Screenshot 2024-01-24 at 11 01 39 PM" src="https://github.com/CarlosNZ/json-edit-react/assets/5456533/b5341f5f-6fdd-4244-95f0-7f42f103f303">

Hope that helps. Please let me know if you have any further problems, or if you have any general feedback regarding the component -- anything confusing, or whatever -- as I'm keen to see how it fares with real-world users.

**Comment by code76kb** [comment] 2024-01-25 04:12
It happen upon click on green btn ,
control doesn't reach the  
`console.log("OnUpdate :", data.newData); `
log and that error message is thrown  

<img width="668" alt="imgg" src="https://github.com/CarlosNZ/json-edit-react/assets/30533545/d988b7a9-86d7-4b81-8730-c0ac68dbdd7d">

<img width="1431" alt="iij" src="https://github.com/CarlosNZ/json-edit-react/assets/30533545/016b1bef-85dc-48ac-ad59-316ac6956728">

**Comment by CarlosNZ** [comment] 2024-01-25 20:21
Hey, I can't reproduce this. Do you get this with my code [above](https://github.com/CarlosNZ/json-edit-react/issues/24#issuecomment-1907803283), or in your own?

**Comment by code76kb** [comment] 2024-01-26 15:48
Yes, this is with the above code

**Comment by CarlosNZ** [comment] 2024-03-03 22:05
Hi @code76kb, wonder if you're still trying to get a resolution to this? Could you try it with the latest version (1.6.1) and see if that makes any difference?

If not, would you be able to fork [this codesandbox](https://codesandbox.io/p/sandbox/json-edit-react-demo-g5qlym?file=%2Fsrc%2FApp.js%3A11%2C11) and see if you can reproduce the problem? If not, then it's probably due something else at your end outside this component.

**Comment by CarlosNZ** [comment] 2024-04-04 07:03
Closing, no follow-up. @code76kb -- please re-open if you're still having problems

**Closed by CarlosNZ** 2024-04-04 07:03 UTC
